HOSTS:
    ubuntu-server:
        roles:
         - master
        platform: ubuntu-12.04-x64
        image: ubuntu:12.04
        hypervisor: docker
        docker_cmd: ['/sbin/init']
        docker_preserve_image: true
        docker_image_commands:
         - wget --no-check-certificate https://apt.puppetlabs.com/puppetlabs-release-precise.deb
         - apt-get install -y wget ca-certificates
         - dpkg -i puppetlabs-release-precise.deb
         - apt-get update
         - apt-get install -y ssh
         - apt-get -y install puppet curl ntpdate git ruby
         - "sed --in-place=.bak 's/without-password/yes/' /etc/ssh/sshd_config"

CONFIG:
  log_level: verbose
  type: foss

